[database.postgres]
host = "127.0.0.1"
port = 5432
user = "postgres"
db_name = "stateway"

[database.s3]
endpoint = "localhost:9000"
access_key_id = "nook"
secret_access_key = "1234567890"

[broker]
gateway_count = 1

[broker.nats]
url = "nats://127.0.0.1:4222"
